src/ScaleVoting/Models/Poll.cs
using System;
using System.ComponentModel.DataAnnotations;
using BCClient;

namespace ScaleVoting.Models
{
    public class Poll
    {
        [Key]
        public Guid Id { get; set; }
        public string Title { get; set; }
        public User User { get; set; }
        public DateTime CreationDate { get; set; }
        public Question[] Questions { get; set;  }
        public BlockChainStatistics Statistics { get; set; }
        
        public Poll(User user, string title, Question[] questions)
        {
            user = User;
            Title = title;
            Questions = questions;
            Id = new Guid();
            CreationDate = DateTime.Now;
        }
    }
}

src/ScaleVoting/Controllers/PollsController.cs
using System;
using System.Threading.Tasks;
using System.Web.Mvc;
using ScaleVoting.BlockChainClient.Client;
using ScaleVoting.Core.ValidationAndPreprocessing.CustomValidators;
using ScaleVoting.Domains;
using ScaleVoting.Extensions;
using ScaleVoting.Infrastucture;
using ScaleVoting.Models;

namespace ScaleVoting.Controllers
{
    public class PollsController : Controller
    {
        private PollDbManager PollDbManager { get; }
        private PollValidator PollValidator { get; }
        private BcClient BcClient { get; }
        private string UserName => HttpContext.User.Identity.Name;

        public PollsController(PollValidator pollValidator)
        {
            PollDbManager = new PollDbManager();
            PollValidator = pollValidator;
            BcClient = new BcClient();
        }

        [Authorize]
        public async Task<ActionResult> Vote(string id)
        {
            Logger.Init();
            try
            {
                var poll = PollDbManager.GetPollWithId(id);

                // TODO Switch to server votecheck logic
                var votes = await BcClient.GetVotesFromDate(poll.TimeStamp);
                poll.Votes = votes;
                ViewBag.Poll = poll;

                ViewBag.UserVoted = poll.HasVoted(UserName);

                return View();
            }
            catch (Exception e)
            {
                Logger.Log.Error(e);
                return Redirect("/ControlPanel");
            }
        }

        [Authorize]
        [HttpPost]
        public async Task<ActionResult> Vote(FormVote formVote)
        {
            Logger.Init();
            try
            {
                var vote = formVote.ToVote(UserName);
                if (!VoteValidator.VoteIsValid(vote, out var messages))
                {
                    var poll = PollDbManager.GetPollWithId(vote.PollId.ToString());
                    ViewBag.Poll = poll;
                    ViewBag.UserVoted = poll.HasVoted(UserName);
                    ViewBag.Errors = messages;
                    return View(formVote);
                }

                await BcClient.SendVoteToBlockChain(vote);
                PollDbManager.AddVotedUser(formVote.PollGuid, Cryptography.Sha256(UserName));

                return Redirect("/");
            }
            catch (Exception e)
            {
                Logger.Log.Error(e);
                return Redirect("/ControlPanel");
            }
        }


        [Authorize]
        public async Task<ActionResult> Stat(string id)
        {
            Logger.Init();
            try
            {
                var poll = PollDbManager.GetPollWithId(id);
                var votes = await BcClient.GetVotesFromDate(poll.TimeStamp);
                poll.Votes = votes;
                var stat = new Statistics(poll);
                ViewBag.stat = stat;

                return View();
            }
            catch (Exception e)
            {
                Logger.Log.Error(e);
                return Redirect("/ControlPanel");
            }
        }

        [Authorize]
        public ActionResult Create()
        {
            return View();
        }

        [Authorize]
        [HttpPost]
        public ActionResult Create(FormPoll model)
        {
            Logger.Init();

            try
            {
                var poll = model.ToPoll(UserName);

                if (!PollValidator.PollIsValid(poll, out var message))
                {
                    ModelState.AddModelError("", message);
                    return View(model);
                }

                PollDbManager.Set(poll);
                ViewBag.Polls = PollDbManager.GetPolls();

                return Redirect("/ControlPanel");
            }
            catch (Exception e)
            {
                Logger.Log.Error(e);
                return Redirect("/ControlPanel");
            }
        }
    }
}

src/ScaleVoting/Views/Polls/Create.cshtml
@using ScaleVoting.Models
@model FormPoll
@Html.ValidationSummary(false)
@{
    ViewBag.Title = "Создать новый опрос";
}
<script>
    var index = 0;

    function appendQuestion(qtype) {
        var current = $('#question-list');
        var element = '';
        // Wrap
        element += '<div id="question-' + index + '" class="question card mb-2">';
        element += '<hidden type="' + qtype + '">';
        element += '<div class="card-header">';
        if (qtype === 'Single') {
            element += 'Вопрос с одним вариантом ответа';
        } else if (qtype === 'Multi') {
            element += 'Вопрос с несколькими вариантами ответа';
        } else {
            element += 'Вопрос со свободным отетом';
        }
        element += "</div>";
        element += '<div class="card-body">';
        // Input title
        element += '<div class="input-group input-group-sm mb-3">' +
            '<div class="input-group-prepend">' +
            '<span class="input-group-text"' +
            'id="question-' +
            index +
            '-title">Заголовок вопроса</span>' +
            '</div><input type="text" class="form-control question-title"' +
            'aria-label="Question title" aria-describedby="question-' +
            index +
            '-title" pattern=".{3,}" required></div>';
        if (qtype === 'Single' || qtype === 'Multi') {
            // Question wrap
            element += '<div id="question-' + index + '-options"></div>';
            // Buttons
            element += '<div class="btn-group" role="group">';
            element += '<button type="button" class="btn btn-primary" onclick="appendOption(' +
                index +
                ');">Добавить опцию</button>';
        }
        element += '<button type="button" class="btn btn-secondary btn-danger" onclick="removeQuestionSingle(' +
            index +
            ');">Удалить вопрос</button>';
        element += '</div>';
        // Close wrap
        element += '</div></div>';
        current.append(element);

        index++;
    }

    function appendOption(id) {
        var target = $('#question-' + id + '-options');
        var element = '';
        // Wrap
        element += '<div class="input-group mb-3">';
        element += '<input type="text" class="form-control option-text" pattern=".{3,}"  required>';
        element +=
            '<div class="input-group-append"><button class="btn btn-outline-secondary" type="button" onclick="removeOption(this);">X</button></div>';
        // Close wrap
        element += '</div>';
        target.append(element);
    }

    function removeOption(elem) {
        elem.parentElement.parentElement.remove();
    }

    function removeQuestionSingle(id) {
        var question = $('#question-' + id);
        question.remove();
    }

    function combineJson() {
        var forms = [];
        var questions = $('.question');
        for (var i = 0; i < questions.length; i++) {
            var form = new Object();
            form.Title = questions[i].getElementsByClassName('question-title')[0].value;
            form.Type = questions[i].getElementsByTagName('hidden')[0].getAttribute('type');
            form.Options = [];
            var optionDivs = questions[i].getElementsByClassName('option-text');
            for (var k = 0; k < optionDivs.length; k++) {
                form.Options[k] = optionDivs[k].value;
            }
            forms[i] = form;
        }
        return JSON.stringify(forms);
    }

    function prepare() {
        var json = combineJson();
        $('#json-questions').val(json);
        return validate();
    }

    function validate() {
        var valid = true;
        var alerts = $('#alerts');
        alerts.empty();
        var questions = $('.question');
        if (questions.length < 1) {
            alerts.append('<div class="alert alert-warning" role="alert">' +
                'Опрос должен содержать хотя бы один вопрос!' +
                '</div>');
            valid = false;
        }
        for (var i = 0; i < questions.length; i++) {
            if (questions[i].firstElementChild.attributes["type"].value === 'Free') {
                continue;
            }
            var options = questions[i].getElementsByClassName('option-text');
            if (options.length < 2) {
                alerts.append('<div class="alert alert-warning" role="alert">' +
                    'В вопросе ' + eval(i+1) + ' должно быть не менее двух вариантов ответа!' +
                    '</div>');
                valid = false;
            }
        }
        return valid;
    }
</script>

<div class="jumbotron">
    <div id="alerts"></div>
    @using (Html.BeginForm())
    {
        @Html.HiddenFor(model => model.JsonQuestions, new {@class = "form-control", id = "json-questions"})
        <div class="input-group input-group mb-3">
            <div class="input-group-prepend">
                <span class="input-group-text" id="inputGroup">Заголовок опроса</span>
            </div>
            @Html.TextBoxFor(model => model.Title, new {@class = "form-control", required = "required", pattern = ".{3,}"})
        </div>

        <div id="question-list"></div>

        <hr class="my-4" id="qbreak"/>

        <div class="btn-group" role="group" aria-label="Poll controls">
            <div class="btn-group" role="group">
                <button id="qselect" type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Добавить вопрос</button>
                <div class="dropdown-menu" aria-labelledby="qselect">
                    <a class="dropdown-item" href="#qselect" onclick="appendQuestion('Single');">Один ответ</a>
                    <a class="dropdown-item" href="#qselect" onclick="appendQuestion('Multi');">Множество ответов</a>
                    <a class="dropdown-item" href="#qselect" onclick="appendQuestion('Free');">Свободный ответ</a>
                </div>
            </div>
            <button type="submit" class="btn btn-primary" onclick="return prepare();">Создать опрос</button>
        </div>
    }
</div>

src/ScaleVoting/Views/Polls/Stat.cshtml
@{
    var stat = ViewBag.Stat;
    var poll = stat.Poll;
    ViewBag.Title = string.Format("Опрос - {0}", Html.Raw(poll.Title));
}
@using ScaleVoting.Domains
@model ScaleVoting.Models.FormVote
@Html.ValidationSummary(false)
 
<div id="poll-@Html.Raw(poll.Guid)" class="jumbotron justify-content-between">
    <h4 class="display-4 text-center">@poll.Title</h4>
    <hr class="my-4">
    @foreach (var question in poll.Questions)
    {
        <div class="card" id="question-@question.Guid">
            <div class="card-header">
                <h5 class="card-title">@question.Title</h5>
            </div>
            <div class="card-body">
                <div class="card-text">
                    @if (question.Type == QuestionType.Single || question.Type == QuestionType.Multi)
                    {
                        <ul class="list-group">
                            @foreach (var option in question.Options)
                            {
                                <li class="list-group-item d-flex justify-content-between align-items-center">
                                    @option.OptionContent
                                    <span class="badge badge-primary badge-pill">@stat.OptionCountStat[option.Guid]</span>
                                </li>
                            }
                        </ul>
                    }
                    else if (question.Type == QuestionType.Free && stat.CustomOptionsList.ContainsKey(question.Guid))
                    {
                        <a class="btn btn-primary" data-toggle="collapse" href="#@question.Guid-free-values" role="button" aria-expanded="false" aria-controls="@question.Guid-free-values">Вывести список ответов</a>
                        <div class="collapse" id="@question.Guid-free-values">
                            <ul class="list-group">
                                @foreach (var value in stat.CustomOptionsList[question.Guid])
                                {
                                    <li class="list-group-item">@value</li>
                                }
                            </ul>
                        </div>
                    }
                    else
                    {
                        <h5 class="text-info">Статистика отсутствует!</h5>
                    }
                </div>
            </div>
        </div>
    }
    <br/>
</div>

src/ScaleVoting/Views/Polls/Vote.cshtml
@{
    var poll = ViewBag.Poll;
    var errors = ViewBag.Errors;
    ViewBag.Title = string.Format("Опрос - {0}", Html.Raw(poll.Title));
}
@using ScaleVoting.Domains
@model ScaleVoting.Models.FormVote
@Html.ValidationSummary(false)

<script>
    function combineJson() {
        var selected = $('.poll-quest-option:checked');
        var list = [];
        for (var i = 0; i < selected.length; i++) {
            list[i] = selected[i].id;
        }
        return JSON.stringify(list);
    }

    function combineJsonCustom() {
        var custom = {};
        var options = $('.free-option');
        for (var i = 0; i < options.length; i++) {
            var guid = options[i].closest('.card').attributes['id'].value;
            var text = options[i].value;
            custom[guid] = text;
        }
        return JSON.stringify(custom);
    }

    function prepare() {
        var json = combineJson();
        var jsonCustom = combineJsonCustom();
        $('#json-options').val(json);
        $('#json-custom').val(jsonCustom);
        return validate();
    }

    function validate() {
        var valid = true;
        var alerts = $('#alerts');
        alerts.empty();
        var questions = $('.card');
        for (var i = 0; i < questions.length; i++) {
            var input = $(questions[i]).find('input');
            if (input.length !== 0) {
                if (!($(input).is(':checked'))) {
                    alerts.append('<div class="alert alert-warning" role="alert">' +
                        'Не выбрана ни одна опция в вопросе ' + eval(i+1) + '!' +
                        '</div>');
                    valid = false;
                }
                continue;
            }
            var text = $(questions[i]).find('textarea')[0].value;
            if (text === '') {
                alerts.append('<div class="alert alert-warning" role="alert">' +
                    'Не введен ответ в вопросе ' + eval(i+1) + '!' +
                    '</div>');
                valid = false;
            }
        }
        return valid;
    }
</script>

@using (Html.BeginForm("Vote", "Polls", FormMethod.Post, new { @class = "needs-validation", validate = "novalidate" }))
{
    @Html.HiddenFor(model => model.PollGuid, new { @class = "form-control", Value = poll.Guid })
    @Html.HiddenFor(model => model.JsonOptions, new { @class = "form-control", id = "json-options" })
    @Html.HiddenFor(model => model.CustomOptions, new { @class = "form-control", id = "json-custom" })
<div id="poll-@Html.Raw(poll.Guid)" class="jumbotron justify-content-between">
    <h4 class="display-4 text-center">@poll.Title</h4>
    <hr class="my-4">
    @if (errors != null)
    {
        foreach (var error in errors)
        {
            <div class="alert alert-warning" role="alert">
                @error
            </div>
        }
    }
    @foreach (var question in poll.Questions)
    {
        <div class="card" id="@question.Guid">
            <div class="card-body">
                <h5 class="card-title">@question.Title</h5>

                <div class="card-text">
                    @if (question.Type == QuestionType.Single)
                    {
                        foreach (var option in question.Options)
                        {
                            <div class="form-check">
                                <input type="radio" class="form-check-input poll-quest-option" name="radio-@question.Guid" id="@option.Guid" />
                                <label for="@option.Guid" class="form-check-label">@option.OptionContent</label>
                            </div>
                            <div class="invalid-feedback">
                                Не выбраны корректные опции
                            </div>
                        }
                    }
                    @if (question.Type == QuestionType.Multi)
                    {
                        foreach (var option in question.Options)
                        {
                            <div class="form-check">
                                <input type="checkbox" class="form-check-input poll-quest-option" name="check-@question.Guid" id="@option.Guid" />
                                <label for="@option.Guid" class="form-check-label">@option.OptionContent</label>
                            </div>
                        }
                    }
                    @if (question.Type == QuestionType.Free)
                    {
                        <div class="form-check">
                            <textarea class="form-control free-option" id="@question.Guid-option"></textarea>
                        </div>
                    }
                </div>
            </div>
        </div>
    }
    <br />
    <div id="alerts"></div>
    <br/>
    @if (ViewBag.UserVoted)
    {
        <div class="alert alert-warning" role="alert">
            Вы уже проголосовали!
        </div>
    }
    else
    {
        if (poll.IsClosed)
        {
            <div class="alert alert-warning" role="alert">
                Опрос был закрыт автором
            </div>
        }
        else
        {
            <button type="submit" class="btn btn-primary" onclick="return prepare()">Голосовать</button>
        }
    }
</div>
}